### ISSUE TITLE
macOS deployment support version?

### ISSUE THREAD

**Issue by andreped** [masadcv/torchmaxflow#4]
As discussed in a previous topic (see [here](https://github.com/HiLab-git/SimpleCRF/pull/8#issuecomment-1088630808)), when you build wheels using the setup.py workflow, as you have done [here](https://github.com/masadcv/torchmaxflow/blob/main/.github/workflows/build-whl-publish.yml), you will run into an issue.

If you look into your released wheels (see [here](https://github.com/masadcv/torchmaxflow/releases/tag/v0.0.4)), you will notice that for the macOS-related wheels there are the files:
[torchmaxflow-0.0.4-cp36-cp36m-macosx_10_14_x86_64.whl](https://github.com/masadcv/torchmaxflow/releases/download/v0.0.4/torchmaxflow-0.0.4-cp36-cp36m-macosx_10_14_x86_64.whl)
and 
[torchmaxflow-0.0.4-cp39-cp39-macosx_10_15_x86_64.whl](https://github.com/masadcv/torchmaxflow/releases/download/v0.0.4/torchmaxflow-0.0.4-cp39-cp39-macosx_10_15_x86_64.whl)

I think the python versions that you use in the workflow are configured to build against specific macOS deployment support versions. Also, AFAIK, the oldest macOS operating system available in GitHub hosted runners is 10.15 ([ref](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)). However, it is possible to build for older versions by setting the MACOS_DEPLOYMENT_TARGET, but I found it quite challenging to set for python projects...

From the same comment by @jamesobutler, and I quote:
"Also in 3D Slicer as of right now soon to be released Slicer 5.0 has minimum support for macOS 10.13. We are actually not using the latest numpy version because it bumped its minimum macOS whl version to macOS 10.14. See https://github.com/Slicer/Slicer/commit/81517ef9a6a4a4d69efce347adc3fce9d03b785e."

I think you need to build wheels with an older macos deployment support version, than you have here. I even think you have two different ones for python3.6-3.8 vs 3.9 (10.14 vs 10.15, see wheels above).

I tried to find a way of fixing this, but in the end what I made run well on macOS 10.13, so it was hard to debug. Any thoughts regarding this?

In a separate project, FAST/pyFAST, the developer managed to set this up correctly, but in the workflow, I believe he had to use pyenv (for workflow, see [here](https://github.com/smistad/FAST/blob/master/.github/workflows/CI-mac.yml#L37), for setup.py, see [here](https://github.com/smistad/FAST/blob/master/source/FAST/Python/setup.py.in#L111)).

---
Lastly, I noted that after installing torchmaxflow, torch is not installed. Is this expected behaviour? Would be nice if dependencies would've been installed if they were not available on the machine. Might be a good idea to setup seperate unit tests to check this for each release.

---
EDIT: There was also a simple fix for the manylinux tag issue mentioned [here](https://github.com/masadcv/torchmaxflow/issues/2#issuecomment-1090635706). However, seems like a simple renaming might not be what you want, due to other issues mentioned in the same thread.
https://github.com/smistad/FAST/blob/master/source/FAST/Python/setup.py.in#L184

**Comment by masadcv** [comment]
Regarding your main question, I dont know how to get earlier macos wheels on github. There could be ways as you describe but it is low priority at the moment. 
The package is provided with sdist (source distribution) and default macos and windows wheels to support commonly used platforms/configurations. If there is a machine that is outside these compiled wheels, the package will automatically switch to compiling from sdist. 

For the purpose of this release, windows wheels were of the highest priority due to issues we have seen with SimpleCRF in MONAI Label -  I have provided these in the release. macos and linux are low priority at the moment, as they can easily compile this library from sdist (if needed). 

Regarding manylinux, I will wait for torch extension builder (https://github.com/charliebudd/torch-extension-builder) as I will switch to it once it supports windows and cpu.

Thanks for the note on dependencies, these are now installed (if not present) during setup.
